// Dev tool: traces the four official emblem tiles (cross, cup, dove, crown) into SVG.
import potrace from 'potrace';
import { writeFileSync, mkdirSync } from 'node:fs';
const tiles = { cross: 'tl', cup: 'tr', dove: 'bl', crown: 'br' };
const out = {};
for (const [name, q] of Object.entries(tiles)) {
  const svg = await new Promise((res, rej) =>
    potrace.trace(`research/emblem-${q}-bw.png`, { threshold: 128, turdSize: 4, optTolerance: 0.3, color: '#fff', background: 'transparent' }, (e, s) => (e ? rej(e) : res(s))),
  );
  const d = svg.match(/ d="([^"]+)"/)[1];
  const vb = svg.match(/viewBox="([^"]+)"/)?.[1] ?? `0 0 ${svg.match(/width="(\d+)"/)[1]} ${svg.match(/height="(\d+)"/)[1]}`;
  out[name] = { d, viewBox: vb };
  mkdirSync('public/brand/emblem', { recursive: true });
  writeFileSync(`public/brand/emblem/${name}.svg`, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}"><path fill="#fff" fill-rule="evenodd" d="${d}"/></svg>`);
}
writeFileSync('src/content/emblem.ts',
  `// Generated by scripts/trace-emblem.mjs from the official logo on foursquare.org.ng.\n// The four symbols of the Foursquare emblem, each traced as one SVG path (white tile, symbol cut out).\nexport const emblem = ${JSON.stringify(out, null, 2)} as const;\n`);
console.log(Object.fromEntries(Object.entries(out).map(([k, v]) => [k, `${v.viewBox} · ${v.d.length} chars`])));
